### ISSUE TITLE
Which Udemy course is this repository based on?

### ISSUE THREAD

**Issue by jeandersonbc** [marcel-reboucas/go-examples#1]
I just found this repository after searching some Go projects because I'm also interested in Go :-)
I noticed by the commit messages that your examples are based in a Go course.
Which Udemy course did you enroll? Do you recommend it?

Thanks in advance!

**Comment by marcel-reboucas** [comment]
Hey Jeanderson,

it is based on this course [Go: The Complete Developer's Guide (Golang)](https://www.udemy.com/go-the-complete-developers-guide/).

The course itself is pretty simple and just scraps the surface of the language syntax, without going into much detail on building go applications. It was quite cheap however, so I decided to give it a chance. I would rate it 3 or 4 stars.

**Comment by jeandersonbc** [comment]
Thanks for the tips @marcel-reboucas!
